- row_title: "Paratoi eich busnes ar gyfer Brexit"
  list_block: |
    Os ydych chi’n mewnforio neu’n allforio nwyddau neu wasanaethau i’r UE, bydd angen i chi sicrhau fod eich busnes yn barod ar gyfer Brexit.

    Er enghraifft, bydd angen i chi weithredu os ydych yn <a href="/prepare-export-from-uk-after-brexit" data-ecommerce-row="true" data-ecommerce-content-id="e169b2ac-8c90-4789-8e6c-3657729e21b2" data-ecommerce-path="/prepare-export-from-uk-after-brexit">allforio nwyddau i’r UE</a> neu’n <a href="/transport-goods-from-uk-by-road" data-ecommerce-row="true" data-ecommerce-content-id="9be67e23-bd76-4d60-b6e1-66e0dce5965a" data-ecommerce-path="/transport-goods-from-uk-by-road">cludo nwyddau allan o’r DU ar y ffyrdd</a>.

    Bydd hefyd angen i chi wirio beth sydd angen i chi wybod os ydych yn <a href="/prepare-import-to-uk-after-brexit" data-ecommerce-row="true" data-ecommerce-content-id="db1149f5-f60a-4d02-be0c-9c9db2828665" datecoa-ecommerce-path="/prepare-import-to-uk-after-brexit">mewnforio nwyddau o’r UE</a> neu'n <a href="/guidance/providing-services-to-any-country-in-the-eu-iceland-liechtenstein-norway-or-switzerland-after-eu-exit" data-ecommerce-row="true" data-ecommerce-content-id="e9dca8c7-04f5-4065-b2ac-70d140512bfa" data-ecommerce-path="/guidance/providing-services-to-any-country-in-the-eu-iceland-liechtenstein-norway-or-switzerland-after-eu-exit">gwerthu gwasanaethau i’r UE.</a>

    Mae rheolau gwahanol i <a href="/guidance/trading-and-moving-from-northern-ireland-to-ireland-in-a-no-deal-brexit" data-ecommerce-row="true" data-ecommerce-content-id="b7b0d001-07a3-4652-81fd-36688aa18b01" data-ecommerce-path="/guidance/trading-and-moving-from-northern-ireland-to-ireland-in-a-no-deal-brexit">symud nwyddau rhwng Iwerddon a Gogledd Iwerddon.</a>
- row_title: "Ymweld â’r UE ar ôl Brexit"
  list_block: |
    I ymweld ag Ewrop ar ôl Brexit, mae pethau sydd angen i chi wneud cyn teithio.

    Bydd angen i chi wirio os oes angen i chi adnewyddu’ch pasport, prynu yswiriant teithio gydag yswiriant gofal iechyd a gwneud yn siŵr fod gennych y dogfennau gyrru cywir.

    [**Gwiriwch beth sydd angen i chi wneud i ymweld ag Ewrop**](/visit-europe-brexit)

- row_title: "Byw a gweithio yn yr UE"
  list_block: |
    Mae byw a gweithio mewn gwlad yr UE yn ddibynnol ar y rheolau yn y wlad honno.

    Efallai bydd angen i chi gofrestru neu gyflwyno cais am breswyliaeth, gwirio os ydych chi’n gymwys am ofal iechyd a chyfnewid eich trwydded yrru DU am drwydded a roddir gan wlad yr UE ble rydych yn byw.

    [**Gwiriwch eich hawliau ar gyfer y wlad yr ydych yn byw ynddi**](/uk-nationals-living-eu)

- row_title: "Aros yn y DU os ydych yn ddinesydd o’r UE"
  list_block: |
    Bydd angen i chi wirio os oes angen i chi gyflwyno cais i’r cynllun setliad os ydych chi neu’ch teulu yn dod o’r UE, Y Swistir, Norwy, Gwlad yr Iâ neu Liechtenstein.

    [**Gwiriwch beth sydd angen i chi wneud i aros yn y DU**](/staying-uk-eu-citizen)
